// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO3zX8L532aKsgUWRQ2o60S3G4K-emLtc',
    appId: '1:231992483691:web:31f79d0d2dc4cb9a3c362e',
    messagingSenderId: '231992483691',
    projectId: 'ai-language-tutor-c8a41',
    authDomain: 'ai-language-tutor-c8a41.firebaseapp.com',
    storageBucket: 'ai-language-tutor-c8a41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3he80Ig_FL5itQg16FSaLsHFTxWoMMIg',
    appId: '1:231992483691:android:dcbaee82e1cccb003c362e',
    messagingSenderId: '231992483691',
    projectId: 'ai-language-tutor-c8a41',
    storageBucket: 'ai-language-tutor-c8a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe856Ixu-u-NkGie8pjuk0wx5u979KvUw',
    appId: '1:231992483691:ios:033d2b459e7ef75e3c362e',
    messagingSenderId: '231992483691',
    projectId: 'ai-language-tutor-c8a41',
    storageBucket: 'ai-language-tutor-c8a41.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe856Ixu-u-NkGie8pjuk0wx5u979KvUw',
    appId: '1:231992483691:ios:033d2b459e7ef75e3c362e',
    messagingSenderId: '231992483691',
    projectId: 'ai-language-tutor-c8a41',
    storageBucket: 'ai-language-tutor-c8a41.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
